services:

  backend:
    build:
      context: .
      dockerfile: DockerFile-backend
    container_name: calendar-backend
    restart: always
    ports:
      - "127.0.0.1:3500:3500"
    command: npm run start-${ENVIRONMENT}

  nginx:
    build:
      context: .
      dockerfile: DockerFile-nginx
      args:
        environment: ${ENVIRONMENT}
    container_name: nginx-reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - nginx-letsencrypt:/etc/letsencrypt
      - type: bind
        source: ./.htpasswd
        target: /etc/nginx/.htpasswd

  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    container_name: calendar-db
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    build:
      context: ./
      dockerfile: Dockerfile-redis
      args:
        redis_pwd: ${REDIS_PASSWORD}
    container_name: calendar-redis
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis:/data

  bullboard:
    image: vaviloff/bullboard_subpath
    container_name: calendar-bullboard
    restart: always
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: calendar-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PROXY_PATH: '/bullboard'
    depends_on:
      - redis


volumes:
  mysql_data:
  redis:
  nginx-letsencrypt:
