filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - decode_json_fields:
      fields: "message"
      target: "json"
      max_depth: 1
      overwrite_keys: true
      process_array: true

output.elasticsearch:
  hosts: ["kibana.vista-point.io:9200"]
  username: "elastic"
  password: "<TODO>"
  indices:
    - index: "calendar-filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false
